Env: dev
Dev:
  CookieHost: 192.168.1.129
  CookieSecure: false
  HttpOnly: false
  CorsHost: http://192.168.1.129:3000
Prod:
  CookieHost: sensei.dviladev.com
  CookieSecure: true
  HttpOnly: true
  CorsHost: https://sensei.dviladev.com:3000
IP: 0.0.0.0
Port: 8080
JwtKey: ${JWT_SECRET}
Mail:
  User: viladevapps@gmail.com
  Pass: ${MAIL_PASS}
  SmtpHost: smtp.gmail.com
  SmtpPort: 587
DB:
  Port: 3306
  Host: db
  User: root
  Pass: ${DB_PASS}
  DB: sensei
