Env: prod
Dev:
  CookieHost: 192.168.1.129
  CookieSecure: false
  HttpOnly: false
  CorsHost: http://192.168.1.129:3000
Prod:
  CookieHost: sensei.dviladev.com
  CookieSecure: true
  HttpOnly: true
  CorsHost: https://sensei.dviladev.com:3000
IP: 0.0.0.0
Port: 8080
JwtKey: senseisecret
Mail:
  User: viladevapps@gmail.com
  SmtpHost: smtp.gmail.com
  SmtpPort: 587
  Enabled: true
  MailTypes:
    AccountActivation:
      Subject: Account activation
      Body: You can use the code %s to validate your Sensei account
    PasswordReset:
      Subject: Password reset
      Body: You can use the code %s to change the password of your Sensei account
DB:
  Port: 3306
  Host: db
  User: root
  Pass: 123456
  DB: sensei
