IP: 0.0.0.0
Port: 8080
JwtKey: sEnSeI258SECRETkey
Mail:
  User: senseitrainingapp@gmail.com
  Pass: emaddwcfyqjexjum
  SmtpHost: smtp.gmail.com
  SmtpPort: 587
 
DB: 
  Host: 172.17.0.1
  Port: 3306
  User: root
  Pass: 1234
  DB: sensei