services:
  db:
      image: mysql:8.0
      restart: always
      volumes:
        - db-volume:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASS}
        MYSQL_DATABASE: sensei
  api: 
    image: sensei-api:latest
    environment:
      DB_PASS: ${DB_PASS}
      MAIL_PASS: ${MAIL_PASS}
      JWT_SECRET: ${JWT_SECRET}
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      
volumes:
  db-volume:
