version: '3.8'

services:
  db:
      image: mysql:8.0
      restart: always
      ports:
        - "3306:3306"
      volumes:
        - db-volume:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: sensei
  api: 
    image: sensei-api:latest
    restart: always
    ports:
      - "8080:8080"

volumes:
  db-volume:
